In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix
dataset = pd.read_csv("heart.csv")
print(dataset.isnull().sum())
data_dup = dataset.duplicated().any()
print(dataset.shape)
print(data_dup)
new_dataset = dataset.drop_duplicates()
print(new_dataset.duplicated().any())
print(new_dataset.shape)

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64
(1025, 14)
True
False
(302, 14)


In [2]:
new_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 302 entries, 0 to 878
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       302 non-null    int64  
 1   sex       302 non-null    int64  
 2   cp        302 non-null    int64  
 3   trestbps  302 non-null    int64  
 4   chol      302 non-null    int64  
 5   fbs       302 non-null    int64  
 6   restecg   302 non-null    int64  
 7   thalach   302 non-null    int64  
 8   exang     302 non-null    int64  
 9   oldpeak   302 non-null    float64
 10  slope     302 non-null    int64  
 11  ca        302 non-null    int64  
 12  thal      302 non-null    int64  
 13  target    302 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 35.4 KB


In [3]:
X = new_dataset.iloc[:, :-1].values
y = new_dataset.iloc[:, -1].values

In [4]:
print(X)

[[52.  1.  0. ...  2.  2.  3.]
 [53.  1.  0. ...  0.  0.  3.]
 [70.  1.  0. ...  0.  0.  3.]
 ...
 [52.  1.  0. ...  2.  1.  3.]
 [59.  1.  3. ...  2.  0.  2.]
 [54.  1.  0. ...  1.  1.  3.]]


In [5]:
print(y)

[0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 1 1 1 0 1 0 0 0 0 0 0 1 0 1 1 1
 0 1 1 0 1 1 1 0 1 0 1 0 1 0 0 1 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 1 1 0 1 0
 0 1 0 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 1 1 1
 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 0 1 1 1 0 1 0 0 1 1 1 1 0 1 1 0 0 0 0 1 0 1
 1 0 0 1 1 1 0 0 1 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 0 1 1
 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 1 1 0 0 0 0 0 1 1
 0 1 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 1 1 0 0 1 0 1
 0 0 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 0 0 1 1 0 0 1 1 1 0 1 1
 0 1 1 0 0 0]


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [7]:
print(X_train)

[[49.  1.  2. ...  2.  3.  2.]
 [69.  1.  3. ...  1.  1.  2.]
 [59.  1.  0. ...  0.  0.  3.]
 ...
 [34.  1.  3. ...  2.  0.  2.]
 [58.  0.  3. ...  2.  0.  2.]
 [60.  1.  0. ...  1.  1.  3.]]


In [8]:
print(X_test)

[[6.50e+01 0.00e+00 2.00e+00 1.55e+02 2.69e+02 0.00e+00 1.00e+00 1.48e+02
  0.00e+00 8.00e-01 2.00e+00 0.00e+00 2.00e+00]
 [5.60e+01 1.00e+00 1.00e+00 1.30e+02 2.21e+02 0.00e+00 0.00e+00 1.63e+02
  0.00e+00 0.00e+00 2.00e+00 0.00e+00 3.00e+00]
 [6.20e+01 0.00e+00 2.00e+00 1.30e+02 2.63e+02 0.00e+00 1.00e+00 9.70e+01
  0.00e+00 1.20e+00 1.00e+00 1.00e+00 3.00e+00]
 [5.80e+01 0.00e+00 2.00e+00 1.20e+02 3.40e+02 0.00e+00 1.00e+00 1.72e+02
  0.00e+00 0.00e+00 2.00e+00 0.00e+00 2.00e+00]
 [5.60e+01 1.00e+00 3.00e+00 1.20e+02 1.93e+02 0.00e+00 0.00e+00 1.62e+02
  0.00e+00 1.90e+00 1.00e+00 0.00e+00 3.00e+00]
 [3.50e+01 1.00e+00 0.00e+00 1.26e+02 2.82e+02 0.00e+00 0.00e+00 1.56e+02
  1.00e+00 0.00e+00 2.00e+00 0.00e+00 3.00e+00]
 [5.70e+01 1.00e+00 1.00e+00 1.24e+02 2.61e+02 0.00e+00 1.00e+00 1.41e+02
  0.00e+00 3.00e-01 2.00e+00 0.00e+00 3.00e+00]
 [5.40e+01 1.00e+00 2.00e+00 1.50e+02 2.32e+02 0.00e+00 0.00e+00 1.65e+02
  0.00e+00 1.60e+00 2.00e+00 0.00e+00 3.00e+00]
 [5.40e+01 1.00e+00 2.00

In [9]:
print(y_train)

[0 1 0 1 1 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0
 1 0 1 0 1 1 1 0 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 0 0
 1 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 0 0
 0 0 1 1 1 1 1 1 0 1 1 1 0 0 1 0 0 1 1 0 1 0 1 0 1 1 1 0 0 0 0 1 1 1 1 1 0
 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 0
 0 0 1 1 1 1 0 0 1 1 1 1 1 0 1 0 1 1 1 0 0 0 1 1 0 1 1 1 1 1 0 1 0 0 0 1 1
 0 0 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0]


In [10]:
print(y_test)

[1 1 0 1 1 0 0 1 1 0 0 1 0 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 1 0 1 1 1
 1 1 1 1 0 0 1 1 1 0 0 1 0 1 1 1 0 0 0 0 0 0 1 1]


In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
print(X_train)

[[-0.56423902  0.67867965  1.08921689 ...  1.00680272  2.35058279
  -0.57005513]
 [ 1.59077847  0.67867965  2.07978772 ... -0.62165     0.3054909
  -0.57005513]
 [ 0.51326972  0.67867965 -0.89192477 ... -2.25010273 -0.71705504
   1.12603483]
 ...
 [-2.18050213  0.67867965  2.07978772 ...  1.00680272 -0.71705504
  -0.57005513]
 [ 0.40551885 -1.47344923  2.07978772 ...  1.00680272 -0.71705504
  -0.57005513]
 [ 0.6210206   0.67867965 -0.89192477 ... -0.62165     0.3054909
   1.12603483]]


In [13]:
print(X_test)

[[ 1.15977497e+00 -1.47344923e+00  1.08921689e+00  1.41948723e+00
   4.35296411e-01 -4.25878561e-01  8.24754293e-01 -6.98113430e-02
  -7.04907377e-01 -2.33301932e-01  1.00680272e+00 -7.17055038e-01
  -5.70055131e-01]
 [ 1.90017102e-01  6.78679645e-01  9.86460579e-02 -2.42012509e-02
  -4.65671362e-01 -4.25878561e-01 -1.06825318e+00  6.06778483e-01
  -7.04907377e-01 -9.13795314e-01  1.00680272e+00 -7.17055038e-01
   1.12603483e+00]
 [ 8.36522348e-01 -1.47344923e+00  1.08921689e+00 -2.42012509e-02
   3.22675440e-01 -4.25878561e-01  8.24754293e-01 -2.37021675e+00
  -7.04907377e-01  1.06944759e-01 -6.21650003e-01  3.05490904e-01
   1.12603483e+00]
 [ 4.05518850e-01 -1.47344923e+00  1.08921689e+00 -6.01676645e-01
   1.76797791e+00 -4.25878561e-01  8.24754293e-01  1.01273238e+00
  -7.04907377e-01 -9.13795314e-01  1.00680272e+00 -7.17055038e-01
  -5.70055131e-01]
 [ 1.90017102e-01  6.78679645e-01  2.07978772e+00 -6.01676645e-01
  -9.91235897e-01 -4.25878561e-01 -1.06825318e+00  5.61672494e-01


In [14]:
from sklearn.linear_model import LogisticRegression
log_classifier = LogisticRegression()
log_classifier.fit(X_train, y_train)
y_pred_log = log_classifier.predict(X_test)
print(accuracy_score(y_test,y_pred_log))
print(confusion_matrix(y_test,y_pred_log))
print(accuracy_score(y_train,log_classifier.predict(X_train)))
print(confusion_matrix(y_train,log_classifier.predict(X_train)))

0.8360655737704918
[[20  5]
 [ 5 31]]
0.8506224066390041
[[ 90  23]
 [ 13 115]]


In [15]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)
y_pred_nb = nb_classifier.predict(X_test)
print(accuracy_score(y_test,y_pred_nb))
print(confusion_matrix(y_test,y_pred_nb))
print(accuracy_score(y_train,nb_classifier.predict(X_train)))
print(confusion_matrix(y_train,nb_classifier.predict(X_train)))

0.8032786885245902
[[20  5]
 [ 7 29]]
0.8298755186721992
[[ 90  23]
 [ 18 110]]


In [16]:
from sklearn.tree import DecisionTreeClassifier
tree_classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
tree_classifier.fit(X_train, y_train)
y_pred_tree = tree_classifier.predict(X_test)
print(accuracy_score(y_test,y_pred_tree))
print(confusion_matrix(y_test,y_pred_tree))
print(accuracy_score(y_train,tree_classifier.predict(X_train)))
print(confusion_matrix(y_train,tree_classifier.predict(X_train)))

0.7868852459016393
[[18  7]
 [ 6 30]]
1.0
[[113   0]
 [  0 128]]


In [17]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=10,criterion='entropy', random_state=0)
rf_classifier.fit(X_train, y_train)
y_pred_rf = rf_classifier.predict(X_test)
print(accuracy_score(y_test,y_pred_rf))
print(confusion_matrix(y_test,y_pred_rf))
print(accuracy_score(y_train,rf_classifier.predict(X_train)))
print(confusion_matrix(y_train,rf_classifier.predict(X_train)))

0.7704918032786885
[[20  5]
 [ 9 27]]
0.983402489626556
[[111   2]
 [  2 126]]


In [18]:
from sklearn.svm import SVC
svc_rbf_classifier = SVC(kernel='rbf',random_state=0)
svc_rbf_classifier.fit(X_train, y_train)
y_pred_svc = svc_rbf_classifier.predict(X_test)
print(accuracy_score(y_test,y_pred_svc))
print(confusion_matrix(y_test,y_pred_svc))
print(accuracy_score(y_train,svc_rbf_classifier.predict(X_train)))
print(confusion_matrix(y_train,svc_rbf_classifier.predict(X_train)))

0.7868852459016393
[[18  7]
 [ 6 30]]
0.921161825726141
[[103  10]
 [  9 119]]


In [19]:
from sklearn.svm import SVC
svc_linear_classifier = SVC(kernel='linear',random_state=0)
svc_linear_classifier.fit(X_train, y_train)
y_pred_svc_linear = svc_linear_classifier.predict(X_test)
print(accuracy_score(y_test,y_pred_svc_linear))
print(confusion_matrix(y_test,y_pred_svc_linear))
print(accuracy_score(y_train,svc_linear_classifier.predict(X_train)))
print(confusion_matrix(y_train,svc_linear_classifier.predict(X_train)))

0.819672131147541
[[19  6]
 [ 5 31]]
0.8506224066390041
[[ 88  25]
 [ 11 117]]


In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn_classifier.fit(X_train, y_train)
y_pred_knn = knn_classifier.predict(X_test)
print(accuracy_score(y_test,y_pred_knn))
print(confusion_matrix(y_test,y_pred_knn))
print(accuracy_score(y_train,knn_classifier.predict(X_train)))
print(confusion_matrix(y_train,knn_classifier.predict(X_train)))

0.819672131147541
[[19  6]
 [ 5 31]]
0.8506224066390041
[[ 91  22]
 [ 14 114]]


In [ ]:
from tkinter import *
from tkinter import messagebox

COLOR = "#e6e6fa"
FONT1 = ("Times New Roman",20,"normal")
FONT = ("Times New Roman",15,"normal")
data_ = []
window = Tk()
window.title("Heart Disease Prediction")
window.config(padx=20, pady=8, bg=COLOR)
def data_function():
    data_.clear()
    try:
        data_.append(int(age.get()))
        data_.append(int(gender.get()))
        data_.append(int(cp.get()))
        data_.append(int(rbp.get()))
        data_.append(int(sch.get()))
        data_.append(int(fbs.get()))
        data_.append(int(rer.get()))
        data_.append(int(maxheart.get()))
        data_.append(int(eia.get()))
        data_.append(float(oldpeak.get()))
        data_.append(int(slope.get()))
        data_.append(int(flo.get()))
        data_.append(int(thal.get()))


    except:
        messagebox.showwarning(message="Wrong input .... Try Again")
    else:
        if log_classifier.predict([data_])[0] == 1:
            result.config(text="Possibility of Heart Disease Is More")
        else:
            result.config(text="Possibility of Heart Disease Is Less")
        
        


heading = Label(text="Heart Disease Prediction",font=FONT1,bg=COLOR)
heading.pack(pady=0)

age = Entry(width=60)
age.insert(0,"Age")
age.pack(pady=8)

gender = Entry(width=60)
gender.insert(0,"Gender (1 = male; 0 = female)")
gender.pack(pady=8)

cp = Entry(width=60)
cp.insert(0,"Chest Pain Type (4 Values)")
cp.pack(pady=8)

rbp = Entry(width=60)
rbp.insert(0,"Resting Blood Pressure")
rbp.pack(pady=8)

sch = Entry(width=60)
sch.insert(0,"Serum Cholesterol in mg/dl")
sch.pack(pady=8)

fbs = Entry(width=60)
fbs.insert(0,"Fasting Blood Sugar > 120 mg/dl (1 = true; 0 = false)")
fbs.pack(pady=8)

rer = Entry(width=60)
rer.insert(0,"Resting Electrocardiograph Results (values 0,1,2)")
rer.pack(pady=8)

maxheart = Entry(width=60)
maxheart.insert(0,"Maximum Heart Rate Achieved")
maxheart.pack(pady=8)

eia = Entry(width=60)
eia.insert(0,"Exercise Induced Angina (1 = yes; 0 = no)")
eia.pack(pady=8)

oldpeak = Entry(width=60)
oldpeak.insert(0,"Old peak = ST depression induced by exercise relative to rest")
oldpeak.pack(pady=8)

slope = Entry(width=60)
slope.insert(0,"The slope of the peak exercise ST segment")
slope.pack(pady=8)

flo = Entry(width=60)
flo.insert(0,"Number of major vessels (0-3) colored by fluoroscopy")
flo.pack(pady=8)

thal = Entry(width=60)
thal.insert(0,"thal: (0 = normal; 1 = fixed defect; 2 = reversible defect)")
thal.pack(pady=8)


submit = Button(text="Submit",command=data_function,highlightthickness=0)
submit.pack(pady=8)

result = Label(text="",font=FONT,bg=COLOR)
result.pack(pady=8)
window.mainloop()